INCLUDE(Configuration.cmake)
INCLUDE(LoadImGui.cmake)

SET(LOGPROPERTIES_NAME "log4cplus.properties")
SET(LOGLEVEL "DEBUG")
SET(LOG_OUTFILE "${PROJECT_BINARY_DIR}/engine.log")
SET(LOG_OUTFILESIZE "10MB")
SET(LOGLAYOUT_ROOT  "%d{%H:%M:%S} [%t] %-5p %c - %m%n")
GENERATE_CONFIG(${LOGPROPERTIES_NAME})

SET(CONFIG_NAME "config.hpp")
SET(ENGINE_BUILD_TYPE dev)
SET(ENGINE_LOGPROPERTIES "${LOGPROPERTIES_NAME}")
SET(ENGINE_PATH "${PROJECT_BINARY_DIR}")
SET(ENGINE_VERSION_MAJOR 1)
SET(ENGINE_VERSION_MINOR 0)
SET(ENGINE_VERSION_PATCH 0)
GENERATE_CONFIG(${CONFIG_NAME})

FIND_PACKAGE(PkgConfig REQUIRED)
pkg_check_modules(SDL3 REQUIRED IMPORTED_TARGET SDL3)
pkg_check_modules(log4cplus REQUIRED IMPORTED_TARGET log4cplus)
FIND_IMGUI(imgui VERSION 1.92.5 DEPS PkgConfig::SDL3 PkgConfig::log4cplus)

ADD_SUBDIRECTORY(core)
ADD_SUBDIRECTORY(ui)

ADD_EXECUTABLE(Engine)
TARGET_INCLUDE_DIRECTORIES(Engine PUBLIC core/include ui/include)
TARGET_SOURCES(Engine PRIVATE main.cpp)
TARGET_LINK_LIBRARIES(Engine EngineCore EngineUI)
