# Given a name of a configuration, calls `CONFIGURE_FILE`
# from the `*.in` variant into to its `*` output
FUNCTION(GENERATE_CONFIG CONFIG_NAME)
MESSAGE("-- Config_Gen: Generating file ${CONFIG_NAME}")
SET(CONFIG_IFILE "${CONFIG_IDIR}/${CONFIG_NAME}.in")
SET(CONFIG_OFILE "${CONFIG_ODIR}/${CONFIG_NAME}")
CONFIGURE_FILE(${CONFIG_IFILE} ${CONFIG_OFILE})
ENDFUNCTION()

SET(CONFIG_IDIR "${CMAKE_CURRENT_SOURCE_DIR}/config")
SET(CONFIG_ODIR "${PROJECT_BINARY_DIR}")
